Remove redundant Ansible Roles, Plays and variables
Remove all reduntant Ansible Roles, Plays, and group/host variable files
from the repository as they are no longer needed or represent old nodes
and configurations of the clusters. This is in preparation for
refactoring and re-deployment of the lab environment systems.

diff --git a/Taskfile.yaml b/Taskfile.yaml
--- a/Taskfile.yaml
+++ b/Taskfile.yaml
@@ -1,59 +1,68 @@
 ---
 version: 3
+output: prefixed
+
+# This Taskfile is configured to minimise dependencies and run most tasks in a
+# semi-sequential way, which reduces issues with parallel task contexts being
+# cancelled following failures. This helps the interval stay low. However, if
+# there are issues with tasks running continuously, or being re-added to the
+# queue multiple times due to regular changes, increase the value for the watch
+# interval to take into account the typical longest running task in the set.
+interval: 2s
+
+# Enforce the pipefail option in the Bash library to ensure that where commands
+# are run through pipes, the failure of any one step in the pipeline fails the
+# whole pipe. For example, terraform |& tee will not normally fail if Terraform
+# fails as tee almost always will exit cleanly, unless pipefail is set.
+set:
+  - pipefail
 
 env:
   limit: '{{ .limit | default "all" }}'
 
+vars:
+  # ANSI Colours
+  cg: \e[0;31m
+  cw: \e[1;37m
+  cc: \e[0m
+
+  # Work out the full path to the root of this repository to allow us to create
+  # absolute paths to configuration files, caches, etc., rather than attempt to
+  # generate relative links programmatically
+  root:
+    sh: git rev-parse --show-toplevel
+
 tasks:
-  pre-checks:
-    desc: Check the environment before running
-    internal: true
+  default:
+    desc: Run the development and integration tasks once
+    summary: |-
+      Clean the environment and then run the development and integration tasks
+      for all resources by testing and checking the code and files, but only
+      once rather than continuously.
+
+      Use the following command for additional information on the steps
+      involved:
+
+      $ task --summary develop
     silent: true
-    run: once
     cmds:
-      - cmd: |-
-          test -x "$(which python 2>/dev/null)" \
-            || (echo "Cannot find 'python'. Please install before trying again."; exit 1)
-      - cmd: |-
-          test -x "$(which pip 2>/dev/null)" \
-            || (echo "Cannot find 'pip'. Please install before trying again."; exit 1)
-      - cmd: |-
-          test -x "$(which pre-commit 2>/dev/null)" \
-            || (echo "Cannot find 'pre-commit'. Please install before trying again."; exit 1)
-      - cmd: |-
-          test -x "$(which ansible 2>/dev/null)" \
-            || (echo "Cannot find 'ansible'. Please install before trying again."; exit 1)
-      - cmd: |-
-          test -x "$(which ansible-playbook 2>/dev/null)" \
-            || (echo "Cannot find 'ansible-playbook'. Please install before trying again."; exit 1)
-      - cmd: |-
-          test -x "$(which sshpass 2>/dev/null)" \
-            || (echo "Cannot find 'sshpass'. Please install before trying again."; exit 1)
-    status:
-      # Setting this file will bypass pre-checks (only use if you are sure)
-      - test -f .skip-pre-checks
+      - task: develop
 
-  deps:
-    desc: Install the required dependencies for the repository
-    cmds:
-      - task: pre-commit
-
-  pre-commit:
-    desc: Add the `pre-commit` hook to this repository
+  develop:
+    desc: Continuously run the development and integration tasks
+    summary: |-
+      The develop task is designed to perform continuous integration on code
+      changes within this repository, first by cleaning the repository and then
+      running the following tasks when any relevant files are changed.
+    silent: true
+    watch: true
     deps:
-      - task: pre-checks
-    cmds:
-      - cmd: pre-commit install
-    generates:
-      - .git/hooks/pre-commit
+      - task: clean
 
   rename:
     desc: Find and rename all .yml files to .yaml
     sources:
-      - "plays/*.yml"
-      - "plays/host_vars/*.yml"
-      - "plays/group_vars/*.yml"
-      - "roles/*/*/*.yml"
+      - "**.yml"
     silent: true
     cmds:
       - cmd: |-
@@ -64,206 +73,15 @@ tasks:
              || mv -f $file ${file%.yml}.yaml
           done
 
-  lint:
-    desc: Run linting tools against the Ansible files
-    summary: |
-      Run linting tools against the Ansible files inside this repository for
-      validity and correctness.
-    run: once
-    deps:
-      - task: pre-checks
-      - task: rename
-    sources:
-      - ".yamllint.yaml"
-      - "plays/*.yaml"
-      - "plays/host_vars/*.yaml"
-      - "plays/group_vars/*.yaml"
-      - "roles/*/*/*.yaml"
-    cmds:
-      - cmd: yamllint --config-file .yamllint.yaml plays/ roles/
-      - cmd: ansible-lint -c .config/ansible-lint.yaml
-
-  ping:
-    desc: Attempt to ping all nodes through Ansible
-    silent: true
-    cmds:
-      - cmd: |-
-          echo -e "Keys:\n" \
-            "  \033[32m   OK       \033[34m   DNS\n" \
-            "  \033[33m   No Route \033[33m   Timeout\n" \
-            "  \033[31m   Refused) \033[31m   Denied" \
-            "\033[0m"
-          echo
-          echo "Pinging all known hosts in the inventory to test for access..."
-      - cmd: |-
-          ansible \
-            --inventory inventory.yaml \
-            --forks 75 \
-            --ask-become-pass \
-            --module-name ansible.builtin.ping \
-            --one-line {{ .limit }} \
-          | awk '
-              /SUCCESS/                    { printf "\033[32m   %s\033[0m\n", $1 }
-              /Could not resolve hostname/ { printf "\033[34m   %s\033[0m\n", $1 }
-              /No route to host/           { printf "\033[33m   %s\033[0m\n", $1 }
-              /Connection refused/         { printf "\033[31m   %s\033[0m\n", $1 }
-              /Connection timed out/       { printf "\033[33m   %s\033[0m\n", $1 }
-              /Permanently added/          { node=$1 }
-              /Permission denied/          { printf "\033[31m   %s\033[0m\n", node }
-          '
-
-  bootstrap:
-    desc: Bootstrap new servers using the bootstrap Ansible Play
-    silent: true
-    cmds:
-      - cmd: |-
-          ansible-playbook \
-            --syntax-check plays/bootstrap.yaml
-      - cmd: |-
-          ansible-playbook \
-            --user root \
-            --ask-pass plays/bootstrap.yaml \
-            --extra-vars bootstrap_chroot_dir=/mnt \
-            --force-handlers \
-            --limit {{ .limit }} \
-            --forks 10
-      # Remove any cached facts after running a bootstrap as the configuration
-      # of the host will change significantly, and a baseline needs a refresh
-      - cmd: rm -rf .cache
-
-  update:
-    desc: Update the pacman package databases on systems
-    silent: true
-    cmds:
-      - cmd: |-
-          ansible-playbook \
-            --syntax-check plays/update.yaml
-      - cmd: |-
-          ansible-playbook \
-            --ask-become-pass plays/update.yaml \
-            --force-handlers \
-            --limit {{ .limit }} \
-            --forks 10
-
-  upgrade:
-    desc: Update and upgrade the packages on systems
-    silent: true
-    cmds:
-      - cmd: |-
-          ansible-playbook \
-            --syntax-check plays/upgrade.yaml
-      - cmd: |-
-          ansible-playbook \
-            --ask-become-pass plays/upgrade.yaml \
-            --force-handlers \
-            --limit {{ .limit }} \
-            --forks 10
-
-  reboot:
-    desc: Update and upgrade the packages on systems
-    silent: true
-    cmds:
-      - cmd: |-
-          echo "This command will initiate a sequential reboot of the following hosts:"
-          ansible --inventory inventory.yaml --list-hosts {{ .limit }} | grep -v '\s\+hosts' | sort
-          read -p "Are you sure? (y/n) " -r
-          echo # Force a new line
-          if [[ ! ${REPLY} =~ ^[Yy] ]]; then
-            exit 1
-          fi
-      - cmd: |-
-          ansible \
-            --inventory inventory.yaml \
-            --forks 1 \
-            --ask-become-pass \
-            --module-name ansible.builtin.reboot \
-            --one-line {{ .limit }}
-
-  baseline:
-    desc: Baseline servers using the baseline Ansible Play
-    silent: true
-    cmds:
-      - cmd: |-
-          ansible-playbook \
-            --syntax-check plays/baseline.yaml
-      - cmd: |-
-          ansible-playbook \
-            --ask-become-pass plays/baseline.yaml \
-            --force-handlers \
-            --limit {{ .limit }} \
-            --forks 10
-
-  users:
-    desc: Update the users and sudo configuration on servers using the users Ansible Play
-    silent: true
-    cmds:
-      - cmd: |-
-          ansible-playbook \
-            --syntax-check plays/users.yaml
-      - cmd: |-
-          ansible-playbook \
-            --ask-become-pass plays/users.yaml \
-            --limit {{ .limit }} \
-            --forks 10
-
-  libvirtd:
-    desc: Configure libvirtd and deploy Virtual Machines
-    silent: true
-    cmds:
-      - cmd: |-
-          ansible-playbook \
-            --syntax-check plays/libvirtd.yaml
-      - cmd: |-
-          ansible-playbook \
-            --ask-become-pass plays/libvirtd.yaml \
-            --limit {{ .limit }} \
-            --forks 10
-
-  kubernetes:
-    desc: Deploy configurations for Kubernetes clusters
-    silent: true
-    cmds:
-      - cmd: |-
-          ansible-playbook \
-            --syntax-check plays/kubernetes.yaml
-      - cmd: |-
-          ansible-playbook \
-            --ask-become-pass plays/kubernetes.yaml \
-            --limit {{ .limit }} \
-            --forks 3
-
-  cache:
-    desc: Deploy configurations for caching proxy
-    silent: true
-    cmds:
-      - cmd: |-
-          ansible-playbook \
-            --syntax-check plays/cache.yaml
-      - cmd: |-
-          ansible-playbook \
-            --ask-become-pass plays/cache.yaml \
-            --limit {{ .limit }} \
-            --forks 3
-
-  netdata:
-    desc: Deploy the Netdata configurations for parents and children
-    silent: true
-    cmds:
-      - cmd: |-
-          ansible-playbook \
-            --syntax-check plays/netdata.yaml
-      - cmd: |-
-          ansible-playbook \
-            --ask-become-pass plays/netdata.yaml \
-            --limit {{ .limit }} \
-            --forks 5
-
   clean:
-    desc: Clean up the temporary files from the repository
-    summary: |
-      Remove any generated configuration files and temporary files from the repository.
-    run: once
+    desc: Clean temporary files from the repository and configurations
     silent: true
+    summary: |-
+      Clean any temporary directories and files created by both this Taskfile,
+      and the tools and applications called from it, and from within the
+      configurations.
+    run: once
     cmds:
-      - cmd: rm -rf .cache
+      - cmd: rm -f .prettiercache
       - cmd: rm -rf .task
+      - cmd: echo -e '{{ .cg }}Completed{{ .cc }}'
